config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :articles do
    resources :comments
  end 
  resources :sessions, only: [:new, :create, :destroy] 
  resources :microposts, only: [:create, :destroy]
  get 'welcome/index'
  match '/about', to: 'welcome#about', via: 'get'
  match '/contact', to: 'welcome#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/users/setPublicKey', to: 'users#setPublicKey', via: 'post'
  

  resources :friendship, only: [:create, :accept, :decline, :cancel, :delete] do
    collection do
      get :create
      get :accept
      get :decline
      get :cancel
      get :delete
    end
  end

  resources :conversations do
    resources :messages
  end
  

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end	
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController


  def index
    @users = User.all
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
	
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.haml
%li.list-group-item.clearfix
  = link_to conversation.subject, conversation_path(conversation)
  .btn-group-vertical.pull-right
    - if conversation.is_trashed?(current_user)
      = link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post
    - else
      = link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete, |
        data: {confirm: 'Are you sure?'}                                                                           |
      - if conversation.is_unread?(current_user)
        = link_to 'Mark as read', mark_as_read_conversation_path(conversation), |
          class: 'btn btn-xs btn-info', method: :post                           |
  %p= render 'conversations/participants', conversation: conversation
  %p
    = conversation.last_message.body
    %small
      (
      %span.text-muted>= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S")
      )

app/views/conversations/_participants.html.haml
- conversation.participants.each do |participant|
  - unless participant == current_user
    = gravatar_for participant

app/views/conversations/index.html.haml
.ui.segment
  %h3 Mailbox
  .ui.list
    .item
      - @conversations.each do |conversation|
        - if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id
          - if conversation.sender_id == current_user.id
            - recipient = User.find(conversation.recipient_id)
          - else
            - recipient = User.find(conversation.sender_id)
          = link_to recipient.name, conversation_messages_path(conversation)
.ui.segment
  %h3 My friends
  .ui.list
    - @users.each do |user|
      - if user.id != current_user.id
        .item
          = user.name
          = link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'

app/views/conversations/show.html.haml
%h2 Conversation
%p
  Chatting with
  \#{render 'conversations/participants', conversation: @conversation}
.panel.panel-default
  .panel-heading= @conversation.subject
  .panel-body
    .messages
      - @conversation.receipts_for(current_user).each do |receipt|
        .media
          - message = receipt.message
          .media-left
            = gravatar_for message.sender, 45, message.sender.name
          .media-body
            %h6.media-heading
              = message.sender.name
              says at #{message.created_at.strftime("%-d %B %Y, %H:%M:%S")}
            = message.body
= form_tag reply_conversation_path(@conversation), method: :post do
  .form-group
    = text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true
  = submit_tag "Send Message", class: 'btn btn-primary'        