config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :articles do
    resources :comments
  end 
  resources :sessions, only: [:new, :create, :destroy] 
  resources :microposts, only: [:create, :destroy]
  get 'welcome/index'
  match '/about', to: 'welcome#about', via: 'get'
  match '/contact', to: 'welcome#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/users/setPublicKey', to: 'users#setPublicKey', via: 'post'
  

  resources :friendship, only: [:create, :accept, :decline, :cancel, :delete] do
    collection do
      get :create
      get :accept
      get :decline
      get :cancel
      get :delete
    end
  end

  resources :conversations do
    resources :messages
  end
  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def about
  end

  def contact
  end	
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>About my Blog</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>
<%= link_to 'Back', welcome_index_path %>

app/views/welcome/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>
<%= link_to 'Back', welcome_index_path %>

app/views/welcome/index.html.haml
!!!
%html
  %head
    %title My Blog
  %body
    - if signed_in?
      .row
        %aside.span4
          %section
            = render 'shared/user_info'
          %section
            = render 'shared/micropost_form'
        .span8
          %h3 Micropost Feed
          = render 'shared/feed'
    - else
      .center
        %h1 Welcome
        %h2
          This is the home page for the My blog.
        = link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary"