config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :articles do
    resources :comments
  end 
  resources :sessions, only: [:new, :create, :destroy] 
  resources :microposts, only: [:create, :destroy]
  get 'welcome/index'
  match '/about', to: 'welcome#about', via: 'get'
  match '/contact', to: 'welcome#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/users/setPublicKey', to: 'users#setPublicKey', via: 'post'
  

  resources :friendship, only: [:create, :accept, :decline, :cancel, :delete] do
    collection do
      get :create
      get :accept
      get :decline
      get :cancel
      get :delete
    end
  end

  resources :conversations do
    resources :messages
  end
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://localhost:3000/welcome/index">Blog</a>
    by Roman Chaban
  </small>
  <nav>
    <ul>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://www.ukr.net/news/tehnologii.html">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "Blog", current_user, id: "logo"
      %nav
        %ul.nav.pull-right
          - if signed_in?
            = link_to 'Create post', welcome_index_path, class: "btn btn-xs btn-info"
            = link_to "Mailbox", conversations_path, class: "btn btn-xs btn-info"
            = link_to 'My Blog', articles_path, class: "btn btn-xs btn-info"
            %li= link_to "Users", users_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to 'My Blog', controller: 'articles'
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Sign out", signout_path, method: "delete"
          - else
            %li= link_to "Sign in", signin_path

app/views/layouts/_nav.html.erb
<div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav pull-right">
    <% if user_signed_in? %>
        <li><%= link_to "Hello, #{current_user.name}", "#" %></li>
        <li><%= link_to "Inbox", mailbox_inbox_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
    <% else %>
        <li class="active"><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
     <% end %>
    </ul>
</div><!--/.nav-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="/assets/jsencrypt.min.js"></script>
  <script type="text/javascript" src="/assets/steganography.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>  
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>